---
permalink: sm-storage/change-configuration-settings-for-a-pool.html 
sidebar: sidebar 
keywords: change, configuration, set, pool 
summary: Você pode editar as configurações de um pool se quiser alterar seu nome, editar as configurações de alertas de capacidade, suas prioridades de modificação ou capacidade de preservação. 
---
= Altere as configurações de um pool
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode editar as configurações de um pool se quiser alterar seu nome, editar as configurações de alertas de capacidade, suas prioridades de modificação ou capacidade de preservação.

.Passos
. Selecione *menu:armazenamento[pools & grupos de volume]*.
. Selecione o pool que você deseja editar e clique em *Exibir/Editar configurações*.
+
A caixa de diálogo *Pool Settings* é exibida.

. Selecione a guia *Configurações* e edite as configurações do pool conforme apropriado.
+
.Detalhes do campo
[%collapsible]
====
[cols="2*"]
|===
| Definição | Descrição 


 a| 
Nome
 a| 
Você pode alterar o nome fornecido pelo usuário do pool. Especificar um nome para um pool é necessário.



 a| 
Alertas de capacidade
 a| 
Você pode enviar notificações de alerta quando a capacidade livre em um pool atingir ou exceder um limite especificado. Quando os dados armazenados no pool excedem o limite especificado, o System Manager envia uma mensagem, permitindo que você adicione mais espaço de armazenamento ou exclua objetos desnecessários.

Os alertas são exibidos na área notificações no Painel de instrumentos e podem ser enviados do servidor para administradores por e-mail e mensagens de intercetação SNMP.

Você pode definir os seguintes alertas de capacidade:

** *Alerta crítico* -- este alerta crítico notifica-o quando a capacidade livre no pool atinge ou excede o limite especificado. Utilize os controlos giratórios para ajustar a percentagem de limiar. Selecione a caixa de verificação para desativar esta notificação.
** *Alerta antecipado* -- este alerta antecipado notifica você quando a capacidade livre em um pool está atingindo um limite especificado. Utilize os controlos giratórios para ajustar a percentagem de limiar. Selecione a caixa de verificação para desativar esta notificação.




 a| 
Prioridades de modificação
 a| 
Você pode especificar os níveis de prioridade para operações de modificação em um pool em relação ao desempenho do sistema. Uma prioridade mais alta para operações de modificação em um pool faz com que uma operação seja concluída mais rápido, mas pode diminuir o desempenho de e/S do host. Uma prioridade menor faz com que as operações demorem mais tempo, mas a performance de e/S do host é menos afetada.

Você pode escolher entre cinco níveis de prioridade: Mais baixo, baixo, médio, alto e mais alto. Quanto maior for o nível de prioridade, maior será o impacto na e/S do host e no desempenho do sistema.

** *Prioridade de reconstrução crítica* -- esta barra deslizante determina a prioridade de uma operação de reconstrução de dados quando várias falhas de unidade resultam em uma condição em que alguns dados não têm redundância e uma falha de unidade adicional pode resultar em perda de dados.
** *Prioridade de reconstrução degradada* -- esta barra deslizante determina a prioridade da operação de reconstrução de dados quando ocorreu uma falha na unidade, mas os dados ainda têm redundância e uma falha adicional na unidade não resulta na perda de dados.
** *Prioridade de operação em segundo plano* -- esta barra deslizante determina a prioridade das operações de fundo do pool que ocorrem enquanto o pool está em um estado ideal. Essas operações incluem expansão dinâmica de volume (DVE), formato de disponibilidade instantânea (IAF) e migração de dados para uma unidade substituída ou adicionada.




 a| 
Capacidade de preservação
 a| 
Você pode definir o número de unidades para determinar a capacidade reservada no pool para dar suporte a possíveis falhas de unidade. Quando ocorre uma falha de unidade, a capacidade de preservação é utilizada para manter os dados reconstruídos. Os pools usam capacidade de preservação durante o processo de reconstrução de dados em vez de unidades hot spare, que são usadas em grupos de volume.

Utilize os controlos giratórios para ajustar o número de unidades. Com base no número de unidades, a capacidade de preservação no pool aparece ao lado da caixa giratória.

Tenha em mente as seguintes informações sobre a capacidade de preservação.

** Como a capacidade de preservação é subtraída da capacidade livre total de um pool, a quantidade de capacidade que você reserva afeta a quantidade de capacidade livre disponível para criar volumes. Se você especificar 0 para a capacidade de preservação, toda a capacidade livre no pool será usada para a criação de volume.
** Se você diminuir a capacidade de preservação, aumentará a capacidade que pode ser usada para volumes de pool.


|===
====
. Clique em *Salvar*.

