---
permalink: sm-storage/create-asynchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, asynchronous, mirrored, volume 
summary: Você espelha um volume assincronamente para manter os dados no storage array remoto para ser uma cópia consistente pontual dos dados no storage array local. Para fazer isso, crie um grupo de consistência de espelhamento para estabelecer a relação de espelhamento entre os dois storage arrays e, em seguida, selecione o volume primário e o volume secundário que você deseja usar no espelhamento. 
---
= Criar volume espelhado assíncrono
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você espelha um volume assincronamente para manter os dados no storage array remoto para ser uma cópia consistente pontual dos dados no storage array local. Para fazer isso, crie um grupo de consistência de espelhamento para estabelecer a relação de espelhamento entre os dois storage arrays e, em seguida, selecione o volume primário e o volume secundário que você deseja usar no espelhamento.

.Antes de começar
* Devem ser definidas as seguintes condições:
+
** O serviço Web Services Proxy está em execução.
** O SANtricity Unified Manager está sendo executado em seu host local por meio de uma conexão HTTPS.
** Cada controlador no array primário e no array secundário deve ter uma porta de gerenciamento Ethernet configurada e estar conetado à rede.
** O Gerenciador Unificado do SANtricity mostra certificados SSL válidos para o storage array. Você pode aceitar um certificado autoassinado ou instalar seu próprio certificado de segurança usando o Unified Manager e navegando para o menu:certificado[Gerenciamento de certificados].
** O Gerenciador de sistemas do SANtricity é iniciado a partir de um Gerenciador unificado.
** Você deve ter descoberto os dois arrays de armazenamento entre os quais deseja espelhar dados. Em seguida, no Unified Manager, você seleciona o storage array do volume primário e clica em *Launch* para abrir o Gerenciador do sistema SANtricity baseado no navegador.


* Você deve saber a senha para os storages de armazenamento local e remoto.
* Seus storage arrays locais e remotos precisam ser conectados por meio de uma malha Fibre Channel ou de uma interface iSCSI.


.Sobre esta tarefa
O processo para espelhar um volume de forma assíncrona é um procedimento de várias etapas:

* <<Passo 1: Crie um grupo de consistência de espelho ou selecione um existente>>
* <<Passo 2: Selecione o volume principal>>
* <<Passo 3: Selecione o volume secundário>>


Um volume pode participar de apenas um relacionamento de espelho.



== Passo 1: Crie um grupo de consistência de espelho ou selecione um existente

[role="lead"]
Você cria um grupo de consistência de espelhamento ou seleciona um existente para estabelecer a relação de espelhamento entre o storage array local e o storage array remoto.

.Sobre esta tarefa
O número de relacionamentos de grupo de consistência de espelho e relacionamentos de pares espelhados que você pode criar depende do hardware em seu storage array.

.Passos
. Execute uma das seguintes ações para acessar a sequência de espelhamento assíncrono:
+
** Selecione menu:armazenamento[Espelhamento assíncrono > criar par espelhado].
** Selecione menu:armazenamento[volumes > Serviços de cópia > Espelhar um volume de forma assíncrona].


. Selecione um grupo de consistência de espelho existente ou crie um novo.
+
Para criar um novo grupo de consistência de espelho, faça o seguinte:

+
.. Insira um nome exclusivo que melhor descreva os dados nos volumes que serão espelhados entre os dois arrays de armazenamento (por exemplo, dados R&D).
.. Selecione a matriz de armazenamento remoto na qual você deseja estabelecer uma relação de espelhamento com a matriz de armazenamento local.
+
[NOTE]
====
Se a matriz de armazenamento remota estiver protegida por palavra-passe, o sistema solicitará uma palavra-passe.

====
.. Escolha se deseja ressincronizar os pares espelhados na matriz de armazenamento remoto manualmente ou automaticamente.
+
*** *Manual* -- você deve atualizar explicitamente a imagem secundária pontual usando a opção de menu ressincronização manual. Selecione esta opção para iniciar manualmente a ressincronização de todos os pares espelhados assíncronos dentro do grupo de espelhos assíncronos.
*** *Automático* -- usando a lista suspensa, especifique a hora desde o início da atualização anterior até o início da próxima atualização. Para alterar o intervalo de sincronização automática do padrão a cada 10 minutos, edite o valor do intervalo, que é definido em minutos.


.. Clique em *criar*.
+
O System Manager cria primeiro o grupo de consistência espelhada no storage array local e cria o grupo de consistência espelhada no storage array remoto.

+
[NOTE]
====
Se o System Manager criar com êxito o grupo de consistência de espelho no storage de armazenamento local, mas não conseguir criá-lo no storage de armazenamento remoto, ele excluirá automaticamente o grupo de consistência de espelho do storage de armazenamento local. Se ocorrer um erro enquanto o System Manager estiver tentando excluir o grupo de consistência de espelho, você deve excluí-lo manualmente.

====


. Selecione *seguinte* e vá para <<Passo 2: Selecione o volume principal>>.




== Passo 2: Selecione o volume principal

[role="lead"]
Você deve selecionar o volume principal que deseja usar na relação de espelhamento e alocar sua capacidade reservada. Todos os volumes adicionados ao grupo de consistência de espelho no storage array local terão a função principal na relação de espelhamento.

.Passos
. Selecione um volume existente que você deseja usar como o volume principal no espelho e clique em *Next* para alocar a capacidade reservada.
. Alocar a capacidade reservada para o volume principal selecionado. Execute uma das seguintes ações:
+
** *Accept the default settings* -- Use esta opção recomendada para alocar a capacidade reservada para o volume primário com as configurações padrão.
** *Aloque suas próprias configurações de capacidade reservada para atender às suas necessidades de armazenamento de dados relacionadas ao espelhamento assíncrono* -- aloque a capacidade reservada usando as diretrizes a seguir.
+
*** A configuração padrão para capacidade reservada é de 20% da capacidade do volume base e, geralmente, essa capacidade é suficiente.
*** A capacidade necessária varia, dependendo da frequência e do tamanho das gravações de e/S no volume principal e por quanto tempo você precisa manter a capacidade.
*** Em geral, escolha uma capacidade maior para a capacidade reservada se uma ou ambas as condições existirem:
+
**** Você pretende manter o par espelhado por um longo período de tempo.
**** Uma grande porcentagem de blocos de dados mudará no volume primário devido à intensa atividade de e/S. Use dados históricos de desempenho ou outros utilitários do sistema operacional para ajudá-lo a determinar a atividade típica de e/S para o volume principal.






. Selecione *seguinte* e vá para <<Passo 3: Selecione o volume secundário>>.




== Passo 3: Selecione o volume secundário

[role="lead"]
Você deve selecionar o volume secundário que deseja usar na relação de espelhamento e alocar sua capacidade reservada. Todos os volumes adicionados ao grupo de consistência de espelho no storage array de armazenamento remoto terão a função secundária na relação de espelhamento.

.Sobre esta tarefa
Quando você seleciona um volume secundário no storage array remoto, o sistema exibe uma lista de todos os volumes elegíveis para esse par espelhado. Quaisquer volumes que não sejam elegíveis para serem usados não são exibidos nessa lista.

.Passos
. Selecione um volume existente que você deseja usar como volume secundário no par espelhado e clique em *Next* para alocar a capacidade reservada.
. Alocar a capacidade reservada para o volume secundário selecionado. Execute uma das seguintes ações:
+
** *Accept the default settings* -- Use esta opção recomendada para alocar a capacidade reservada para o volume secundário com as configurações padrão.
** *Aloque suas próprias configurações de capacidade reservada para atender às suas necessidades de armazenamento de dados relacionadas ao espelhamento assíncrono* -- aloque a capacidade reservada usando as diretrizes a seguir.
+
*** A configuração padrão para capacidade reservada é de 20% da capacidade do volume base e, geralmente, essa capacidade é suficiente.
*** A capacidade necessária varia, dependendo da frequência e do tamanho das gravações de e/S no volume principal e por quanto tempo você precisa manter a capacidade.
*** Em geral, escolha uma capacidade maior para a capacidade reservada se uma ou ambas as condições existirem:
+
**** Você pretende manter o par espelhado por um longo período de tempo.
**** Uma grande porcentagem de blocos de dados mudará no volume primário devido à intensa atividade de e/S. Use dados históricos de desempenho ou outros utilitários do sistema operacional para ajudá-lo a determinar a atividade típica de e/S para o volume principal.






. Selecione *Finish* para concluir a sequência de espelhamento assíncrono.


.Resultados
O System Manager executa as seguintes ações:

* Inicia a sincronização inicial entre a matriz de armazenamento local e a matriz de armazenamento remoto.
* Se o volume espelhado for um volume fino, apenas os blocos provisionados (capacidade alocada em vez de capacidade reportada) serão transferidos para o volume secundário durante a sincronização inicial. Isso reduz a quantidade de dados que devem ser transferidos para concluir a sincronização inicial.
* Cria a capacidade reservada para o par espelhado no storage array local e no storage array remoto.

