---
permalink: sm-storage/create-synchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, synchronous, mirrored, volume 
summary: Você espelha um volume de forma síncrona para replicar dados em tempo real entre os storage arrays, para que suas informações fiquem protegidas contra falhas do sistema e do local. Para fazer isso, selecione o volume principal e o volume secundário que deseja usar na relação de espelhamento síncrono entre um storage array local e um storage array remoto. 
---
= Criar volume espelhado síncrono
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você espelha um volume de forma síncrona para replicar dados em tempo real entre os storage arrays, para que suas informações fiquem protegidas contra falhas do sistema e do local. Para fazer isso, selecione o volume principal e o volume secundário que deseja usar na relação de espelhamento síncrono entre um storage array local e um storage array remoto.

.Antes de começar
* Como o recurso espelhamento síncrono exige o gerenciamento de vários storage arrays, você precisa ter o SANtricity Unified Manager instalado com base em navegador e descobrir os dois storage arrays entre os quais deseja espelhar os dados. Em seguida, no Unified Manager, você seleciona o storage array do volume primário e clica em *Launch* para abrir o Gerenciador do sistema SANtricity baseado no navegador.
* Você precisa ter dois storage arrays.
* Cada storage array deve ter duas controladoras.
* Os storage arrays de volumes primário e secundário podem executar diferentes versões do sistema operacional. A versão mínima suportada é 7,84.
* Você deve saber a senha para os storages de armazenamento local e remoto.
* Seus storage arrays locais e remotos precisam ser conectados por uma malha Fibre Channel.
* Você precisa ter criado os volumes primário e secundário que deseja usar na relação de espelhamento síncrono.


.Sobre esta tarefa
O processo para espelhar um volume de forma síncrona é um procedimento de várias etapas:

* <<Passo 1: Selecione o volume principal>>
* <<Passo 2: Selecione o volume secundário>>
* <<Passo 3: Selecione as configurações de sincronização>>


Um volume pode participar de apenas um relacionamento de espelho.



== Passo 1: Selecione o volume principal

[role="lead"]
Você deve selecionar o volume principal que deseja usar na relação de espelhamento síncrono. Este volume tem o papel principal na relação de espelho.

.Antes de começar
* Você deve ter criado o volume principal que deseja usar na relação de espelhamento síncrono.
* O volume primário deve ser um volume padrão. Não pode ser um volume fino ou um volume instantâneo.


.Passos
. Execute uma das seguintes ações para acessar a sequência de espelhamento síncrono:
+
** Selecione menu:armazenamento[Espelhamento síncrono > volume do espelho].
** Selecione menu:armazenamento[volumes > Serviços de cópia > Espelhar um volume de forma síncrona]. A caixa de diálogo *Create Synchronous Mirrored Pair* é exibida.


. Selecione um volume existente que você deseja usar como o volume principal no espelho.
+
[NOTE]
====
Se um volume foi selecionado no bloco volumes e for elegível para ser espelhado, ele será selecionado por padrão.

====
. Selecione *seguinte* e vá para <<Passo 2: Selecione o volume secundário>>.




== Passo 2: Selecione o volume secundário

[role="lead"]
Você deve selecionar o volume secundário que deseja usar na relação de espelhamento. Este volume terá o papel secundário na relação do espelho.

.Antes de começar
* Você deve ter criado o volume secundário que deseja usar na relação de espelhamento síncrono.
* O volume secundário deve ser um volume padrão. Não pode ser um volume fino ou um volume instantâneo.
* O volume secundário deve ser pelo menos tão grande quanto o volume primário.


.Sobre esta tarefa
Quando você seleciona um volume secundário no storage array remoto, o sistema exibe uma lista de todos os volumes elegíveis para esse par espelhado. Quaisquer volumes que não sejam elegíveis para serem usados não são exibidos nessa lista.

Os volumes que aparecem nesta caixa de diálogo são ordenados por capacidade, começando pelo volume mais próximo da capacidade da capacidade do volume primário. Volumes com capacidade idêntica são ordenados alfabeticamente.

.Passos
. Selecione a matriz de armazenamento remoto na qual você deseja estabelecer uma relação de espelhamento com a matriz de armazenamento local.
+
[NOTE]
====
Se a matriz de armazenamento remota estiver protegida por palavra-passe, o sistema solicitará uma palavra-passe.

====
+
** Os storage arrays são listados pelo nome do storage array. Se você não nomeou um storage array, ele será listado como "sem nome".
** Se a matriz de armazenamento que você deseja usar não estiver na lista, adicione-a usando a janela de Gerenciamento Empresarial (EMW) do SANtricity Storage Manager. Selecione menu:Editar[Add Storage Array] (Adicionar matriz de armazenamento).


. Selecione um volume existente que você deseja usar como volume secundário no espelho.
+
[NOTE]
====
Se um volume secundário for escolhido com uma capacidade maior que o volume primário, a capacidade utilizável será restrita ao tamanho do volume primário.

====
. Clique em *seguinte* e vá para <<Passo 3: Selecione as configurações de sincronização>>.




== Passo 3: Selecione as configurações de sincronização

[role="lead"]
Você deve definir a prioridade na qual o proprietário do controlador do volume primário ressincroniza os dados com o volume secundário após uma interrupção de comunicação. Você também deve selecionar a política de ressincronização, manual ou automática.

.Passos
. Utilize a barra deslizante para definir a prioridade de sincronização.
+
A prioridade de sincronização determina quanto dos recursos do sistema são usados para concluir a sincronização inicial e a operação de ressincronização após uma interrupção de comunicação em comparação com as solicitações de e/S de serviço.

+
A prioridade definida nesta caixa de diálogo aplica-se tanto ao volume primário como ao volume secundário. Pode modificar a taxa no volume principal posteriormente selecionando menu:armazenamento[Espelhamento síncrono > mais > Editar definições].

+
.Mais sobre as taxas de sincronização
[%collapsible]
====
Existem cinco taxas de prioridade de sincronização:

** Mais baixo
** Baixo
** Média
** Alta
** Maior se a prioridade de sincronização for definida para a taxa mais baixa, a atividade de e/S será priorizada e a operação de ressincronização demorará mais tempo. Se a prioridade de sincronização estiver definida para a taxa mais alta, a operação de ressincronização será priorizada, mas a atividade de e/S para o storage array pode ser afetada.


====
. Escolha se deseja ressincronizar os pares espelhados na matriz de armazenamento remoto manualmente ou automaticamente.
+
** *Manual* (a opção recomendada) -- Selecione essa opção para exigir que a sincronização seja reiniciada manualmente após a comunicação ser restaurada para um par espelhado. Essa opção oferece a melhor oportunidade para recuperar dados.
** *Automático* -- Selecione esta opção para iniciar a ressincronização automaticamente após a comunicação ser restaurada para um par espelhado. Para retomar manualmente a sincronização, vá para o menu:armazenamento[Espelhamento síncrono], realce o par espelhado na tabela e selecione *Resume* em *More*.


. Clique em *Finish* para concluir a sequência de espelhamento síncrono.


.Resultados
O System Manager executa as seguintes ações:

* Ativa a funcionalidade de espelhamento síncrono.
* Inicia a sincronização inicial entre a matriz de armazenamento local e a matriz de armazenamento remoto.
* Define a prioridade de sincronização e a política de ressincronização.


.Depois de terminar
Selecione menu:Home[View Operations in Progress] (Ver operações em curso) para ver o progresso da operação de espelhamento síncrono. Esta operação pode ser demorada e pode afetar o desempenho do sistema.
