---
permalink: sm-storage/what-is-data-assurance.html 
sidebar: sidebar 
keywords: data, assurance 
summary: 'O Data Assurance (DA) verifica e corrige erros que podem ocorrer à medida que os dados são comunicados entre um host e um storage array. As capacidades DA são apresentadas no nível de grupo de volume e pool no System Manager.' 
---
= O que é o Data Assurance?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Data Assurance (DA) verifica e corrige erros que podem ocorrer à medida que os dados são comunicados entre um host e um storage array. As capacidades DA são apresentadas no nível de grupo de volume e pool no System Manager.

O recurso Data Assurance (DA) aumenta a integridade dos dados em todo o sistema de armazenamento. O DA permite que o storage array verifique se há erros que possam ocorrer quando os dados são movidos entre os hosts e as unidades. Quando esse recurso está ativado, o storage de armazenamento anexa códigos de verificação de erros (também conhecidos como verificações de redundância cíclica ou CRCs) a cada bloco de dados no volume. Depois que um bloco de dados é movido, o storage array usa esses códigos CRC para determinar se ocorreram erros durante a transmissão. Os dados potencialmente corrompidos não são gravados no disco nem devolvidos ao host.

Se você quiser usar o recurso DA, selecione um pool ou grupo de volume que seja capaz de DA quando você criar um novo volume (procure *Sim* ao lado DE DA na tabela de candidatos ao grupo de grupo de volume e pool).

Certifique-se de atribuir esses volumes habilitados PARA DA a um host usando uma interface de e/S capaz de DA. As interfaces de e/S capazes de DA incluem Fibre Channel, SAS, iSCSI em TCP/IP e iSER em InfiniBand (iSCSI Extensions for RDMA/IB). DA não é compatível com SRP em InfiniBand.
