---
permalink: sm-mirroring/considerations-for-setting-up-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: considerations, setting up, asynchronous, mirror 
summary: Para garantir uma configuração e configuração bem-sucedidas, tenha em mente algumas considerações importantes como parte do seu Planejamento. 
---
= Considerações para configurar o espelhamento assíncrono
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para garantir uma configuração e configuração bem-sucedidas, tenha em mente algumas considerações importantes como parte do seu Planejamento.



== Inicie o SANtricity Unified Manager

* Cada controlador no array primário e no array secundário deve ter uma porta de gerenciamento Ethernet configurada e estar conetado à rede.
* O espelhamento assíncrono é configurado abrindo o SANtricity Unified Manager. Qualquer relação de espelhamento requer que os sistemas de storage local e remoto sejam descobertos e listados no SANtricity Unified Manager.
* Você precisa ter o SANtricity Unified Manager baseado no navegador instalado e ter descoberto os dois arrays de storage entre os quais deseja espelhar dados. Em seguida, no Unified Manager, você seleciona o storage array do volume principal e clica em Iniciar para abrir o Gerenciador de sistema do SANtricity baseado no navegador.




== A ativar

Antes de usar o espelhamento assíncrono, você precisa ativá-lo em cada storage array que participe de operações de espelhamento. A ativação pode ser feita por meio da CLI, API REST ou interface gráfica do usuário (GUI) de gerenciamento.

* Para sistemas gerenciados pelo Gerenciador de sistemas do SANtricity (E2800, E5700, EF570), não é necessária nenhuma etapa de ativação separada; a ativação ocorre nos bastidores enquanto grupos/pares de espelhos estão sendo configurados.
* Para sistemas gerenciados pelo SANtricity Storage Manager (E2700, E5600, EF560), o espelhamento assíncrono é ativado usando a GUI no sistema legado que não é gerenciado pelo Gerenciador de sistema do SANtricity. Se estiver usando iSCSI para espelhamento assíncrono, a etapa de ativação não será necessária.




== Certificados de serviços da Web e navegadores recomendados

* *Certificados confiáveis*
+
Para espelhamento envolvendo sistemas gerenciados pelo Gerenciador de sistemas do SANtricity, recomenda-se importar os certificados confiáveis para os serviços da Web no Gerenciador Unificado do SANtricity que permitem que os sistemas de storage se autentiquem com o servidor da Web. As etapas do Gerenciador Unificado do SANtricity são as seguintes:

+
.. Gere uma solicitação de assinatura de certificado (CSR) para a máquina em que o Gerenciador Unificado do SANtricity está instalado.
.. Envie o CSR para uma autoridade de certificação (CA).
.. Quando a CA envia de volta os certificados assinados, importe-os no Unified Manager.


* *Certificados autoassinados*
+
Certificados autoassinados também podem ser usados. Se o administrador tentar configurar o espelhamento sem importar certificados assinados, o Gerenciador de sistema do SANtricity exibirá uma caixa de diálogo de erro que permite que o administrador aceite o certificado autoassinado. Neste caso, é recomendável usar a versão mais recente do Chrome ou Firefox como navegador.

+
Você pode aceitar um certificado autoassinado ou instalar seu próprio certificado de segurança usando o Unified Manager e navegando para o menu:certificado[Gerenciamento de certificados].





== Conexões suportadas

O espelhamento assíncrono pode usar conexões FC ou iSCSI ou ambas para comunicação entre sistemas de storage locais e remotos. No momento da criação de um grupo de consistência de espelho (também conhecido como grupo de espelhamento assíncrono), o administrador pode selecionar FC ou iSCSI para esse grupo se ambos estiverem conetados ao storage array remoto. Não há failover de um tipo de canal para o outro.

O espelhamento assíncrono usa as portas de e/S do host do storage array para transmitir dados espelhados do lado principal para o lado secundário.

* *Espelhamento por uma interface Fibre Channel (FC)*
+
Cada controladora do storage array dedica sua porta de host FC de maior número às operações de espelhamento.

+
Se o controlador tiver portas FC de base e portas FC da placa de interface do host (HIC), a porta numerada mais alta estará em um HIC. Qualquer host conetado à porta dedicada é desconetado e nenhuma solicitação de login do host é aceita. As solicitações de e/S nessa porta são aceitas somente de controladores que participam de operações de espelhamento.

+
As portas de espelhamento dedicadas devem ser conectadas a um ambiente de malha FC que suporte as interfaces do serviço de diretório e serviço de nomes. Em particular, FC-AL e ponto a ponto não são compatíveis como opções de conectividade entre as controladoras que estão participando de relacionamentos espelhados.

* *Espelhamento através de uma interface iSCSI*
+
Ao contrário do FC, o iSCSI não requer uma porta dedicada. Quando o espelhamento assíncrono é usado em ambientes iSCSI, não é necessário dedicar nenhuma das portas iSCSI de front-end do storage array para uso com espelhamento assíncrono. Essas portas são compartilhadas para tráfego de espelhamento assíncrono e conexões de e/S de host para array.

+
O controlador mantém uma lista de sistemas de armazenamento remoto com os quais o iniciador iSCSI tenta estabelecer uma sessão. A primeira porta que estabelece com êxito uma conexão iSCSI é usada para toda a comunicação subsequente com esse storage de armazenamento remoto. Se a comunicação falhar, uma nova sessão é tentada usando todas as portas disponíveis.

+
As portas iSCSI são configuradas no nível da matriz, porta a porta. A comunicação entre controladores para mensagens de configuração e transferência de dados usa as configurações globais, incluindo configurações para:

+
** VLAN: Os sistemas locais e remotos devem ter a mesma configuração de VLAN para se comunicar
** Porta de escuta iSCSI
** Jumbo Frames
** Prioridade Ethernet


+
[NOTE]
====
A comunicação do intercontrolador iSCSI deve usar uma porta de conexão de host e não a porta Ethernet de gerenciamento.

====


O espelhamento assíncrono usa as portas de e/S do host do storage array para transmitir dados espelhados do lado principal para o lado secundário. Como o espelhamento assíncrono é destinado a redes de maior latência e de menor custo, as conexões iSCSI (e, portanto, baseadas em TCP/IP) são uma boa opção para isso. Quando o espelhamento assíncrono é usado em ambientes iSCSI, não é necessário dedicar nenhuma das portas iSCSI de front-end do array para uso com espelhamento assíncrono; essas portas são compartilhadas para tráfego de espelhamento assíncrono e conexões de e/S de host para array
