---
permalink: sm-mirroring/what-do-i-need-to-know-before-creating-a-mirror-consistency-group.html 
sidebar: sidebar 
keywords: creating,  mirror, consistency group 
summary: Você precisa ter o SANtricity Unified Manager baseado no navegador instalado e ter descoberto os dois arrays de storage entre os quais deseja espelhar dados. Em seguida, no Unified Manager, você seleciona o storage array do volume principal e clica em Iniciar para abrir o Gerenciador de sistema do SANtricity baseado no navegador. 
---
= O que eu preciso saber antes de criar um grupo de consistência de espelho?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você precisa ter o SANtricity Unified Manager baseado no navegador instalado e ter descoberto os dois arrays de storage entre os quais deseja espelhar dados. Em seguida, no Unified Manager, você seleciona o storage array do volume principal e clica em Iniciar para abrir o Gerenciador de sistema do SANtricity baseado no navegador.

Além disso, certifique-se do seguinte:

* Você precisa ter capacidade livre suficiente no storage array remoto para criar um volume secundário igual ou maior que o volume principal que deseja espelhar.
* Você precisa ter dois storage arrays.
* Cada storage array deve ter duas controladoras.
* Você deve saber a senha para os storages de armazenamento local e remoto.
* Seus storage arrays locais e remotos precisam ser conectados por meio de uma malha Fibre Channel ou de uma interface iSCSI.

