---
permalink: sm-hardware/configure-nvme-over-roce-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, roce, ports 
summary: 'Se o controlador incluir uma conexão para NVMe em RoCE (RDMA em Converged Ethernet), você poderá configurar as configurações da porta NVMe na página hardware ou na página sistema.' 
---
= Configurar o NVMe em portas RoCE
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se o controlador incluir uma conexão para NVMe em RoCE (RDMA em Converged Ethernet), você poderá configurar as configurações da porta NVMe na página hardware ou na página sistema.

.Antes de começar
* Sua controladora deve incluir uma porta de host NVMe em RoCE; caso contrário, as configurações NVMe em RoCE não estarão disponíveis no System Manager.
* Você deve saber o endereço IP da conexão do host.


.Sobre esta tarefa
Você pode acessar a configuração NVMe sobre RoCE na página hardware ou no menu:Configurações[sistema]. Esta tarefa descreve como configurar as portas a partir da página *hardware*.

[NOTE]
====
As configurações e funções do NVMe em RoCE só aparecerão se a controladora do storage array incluir uma porta NVMe em RoCE.

====
.Passos
. Selecione *hardware*.
. Se o gráfico mostrar as unidades, clique em *Mostrar parte traseira da prateleira*.
+
O gráfico muda para mostrar os controladores em vez das unidades.

. Clique no controlador com a porta NVMe sobre RoCE que você deseja configurar.
+
É apresentado o menu de contexto do controlador.

. Selecione *Configure NVMe over RoCE ports*.
+
A caixa de diálogo * Configurar portas NVMe em RoCE é aberta.

. Na lista suspensa, selecione a porta HIC que deseja configurar.
. Clique em *seguinte*.
+
Para ver todas as configurações de porta, clique no link Mostrar mais configurações de porta à direita da caixa de diálogo.

+
.Detalhes do campo
[%collapsible]
====
|===
| Definição da porta | Descrição 


 a| 
Velocidade da porta ethernet configurada
 a| 
Selecione a velocidade que corresponde à capacidade de velocidade do SFP na porta.



 a| 
Ativar IPv4 / ativar IPv6
 a| 
Selecione uma ou ambas as opções para ativar o suporte para redes IPv4G e IPv6G.


NOTE: Se pretender desativar o acesso à porta, desmarque ambas as caixas de verificação.



 a| 
Tamanho da MTU (disponível clicando em Mostrar mais configurações de porta.)
 a| 
Se necessário, introduza um novo tamanho em bytes para a unidade máxima de transmissão (MTU).

O tamanho padrão da unidade máxima de transmissão (MTU) é de 1500 bytes por quadro. Tem de introduzir um valor entre 1500 e 9000.

|===
====
+
Se você selecionou Ativar IPv4, uma caixa de diálogo será aberta para selecionar IPv4 configurações depois de clicar em Avançar. Se você selecionou Ativar IPv6, uma caixa de diálogo será aberta para selecionar IPv6 configurações depois de clicar em Avançar. Se você selecionou ambas as opções, a caixa de diálogo para configurações IPv4 será aberta primeiro e, depois de clicar em Avançar, a caixa de diálogo para configurações IPv6 será aberta.

. Configure as definições IPv4 e/ou IPv6, automática ou manualmente.
+
.Detalhes do campo
[%collapsible]
====
|===
| Definição da porta | Descrição 


 a| 
Obter automaticamente a configuração
 a| 
Selecione esta opção para obter a configuração automaticamente.



 a| 
Especifique manualmente a configuração estática
 a| 
Selecione esta opção e, em seguida, introduza um endereço estático nos campos. (Se desejado, você pode cortar e colar endereços nos campos.) Para IPv4, inclua a máscara de sub-rede e o gateway. Para IPv6, inclua o endereço IP roteável e o endereço IP do roteador.

|===
====
. Clique em *Finish*.

