---
permalink: sm-settings/reset-management-certificates.html 
sidebar: sidebar 
keywords: reset, management, certificates 
summary: Você pode reverter os certificados de gerenciamento na matriz de armazenamento de volta para o estado autoassinado de fábrica. 
---
= Repor certificados de gestão
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode reverter os certificados de gerenciamento na matriz de armazenamento de volta para o estado autoassinado de fábrica.

.Antes de começar
* Você deve estar conetado com um perfil de usuário que inclua permissões de administrador de segurança. Caso contrário, as funções do certificado não aparecem.
* Os certificados devem ser importados anteriormente.


.Sobre esta tarefa
A redefinição dos certificados de gerenciamento na matriz de armazenamento exclui os certificados de gerenciamento atuais de cada um dos controladores. Depois que os certificados são redefinidos, os controladores revertem para o uso de certificados autoassinados.

.Passos
. Selecione menu:Definições[certificados].
. Na guia *Array Management*, selecione *Reset*.
+
Uma caixa de diálogo *Confirm Reset Management Certificates* é aberta.

. Digite `reset` o campo e clique em *Reset*.


.Resultados
Após a atualização do navegador, os controladores revertem para o uso de certificados autoassinados. Como resultado, o sistema solicita aos usuários que aceitem manualmente o certificado autoassinado para suas sessões.
