---
permalink: sm-settings/view-nvme-over-fabrics-statistics-support.html 
sidebar: sidebar 
keywords: view, nvme, over, fabrics, statistics 
summary: É possível visualizar dados sobre as conexões NVMe sobre Fabrics com o storage array. 
---
= Veja as estatísticas do NVMe sobre Fabrics
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
É possível visualizar dados sobre as conexões NVMe sobre Fabrics com o storage array.

.Sobre esta tarefa
O System Manager mostra esses tipos de estatísticas de NVMe sobre Fabrics. Todas as estatísticas são apenas de leitura e não podem ser definidas.

* *Estatísticas do NVMe Subsystem* -- fornece estatísticas para a controladora NVMe, incluindo tempos limite e falhas de conexão.
* *Estatísticas da interface RDMA* -- fornece estatísticas para a interface RDMA, incluindo informações de pacotes recebidos e transmitidos.


Você pode visualizar cada uma dessas estatísticas como estatísticas em bruto ou como estatísticas de linha de base. As estatísticas em bruto são todas as estatísticas que foram coletadas desde que os controladores foram iniciados. As estatísticas da linha de base são estatísticas pontuais que foram reunidas desde que você definiu o tempo da linha de base.

Você pode acessar as estatísticas do NVMe sobre Fabrics na página sistema (menu:Configurações[sistema]) ou na página suporte. Estas instruções descrevem como aceder às estatísticas a partir da página de suporte.

.Passos
. Selecione menu:guia Support [Support Center > Diagnostics] (suporte > Centro de suporte > Diagnóstico).
. Selecione *View NVMe over Fabrics Statistics*.
. Para definir a linha de base, clique em *Definir nova linha de base*.
+
Definir a linha de base define um novo ponto de partida para a coleção das estatísticas. A mesma linha de base é usada para todas as estatísticas do NVMe.


