---
permalink: sm-settings/what-else-do-i-need-to-do-to-configure-or-diagnose-nvme-over-infiniband.html 
sidebar: sidebar 
keywords: what, else, need, configure, diagnose, nvme, infiniband 
summary: A tabela a seguir lista as funções do System Manager que você pode usar para configurar e gerenciar sessões NVMe over InfiniBand. 
---
= O que mais preciso fazer para configurar ou diagnosticar o NVMe em InfiniBand?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A tabela a seguir lista as funções do System Manager que você pode usar para configurar e gerenciar sessões NVMe over InfiniBand.

[NOTE]
====
As configurações NVMe over InfiniBand estarão disponíveis somente se a controladora do storage array incluir uma porta NVMe over InfiniBand.

====


== Configurar e diagnosticar o NVMe em InfiniBand

[cols="25h,~"]
|===
| Ação | Localização 


 a| 
Configurar portas NVMe em InfiniBand
 a| 
. Selecione *hardware*.
. Selecione *Mostrar parte posterior da prateleira*.
. Selecione um controlador.
. Selecione *Configurar portas NVMe over InfiniBand*.


ou

. Selecione menu:Definições[sistema].
. Role para baixo até *NVMe over InfiniBand settings* e selecione *Configurar portas NVMe over InfiniBand*.




 a| 
Visualizar estatísticas do NVMe em InfiniBand
 a| 
. Selecione menu:Definições[sistema].
. Role para baixo até *NVMe over InfiniBand settings* e selecione *View NVMe over Fabrics Statistics*.


|===